name: Build and Release Python Executables

on:
  push:
    branches:
      - main
      
permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          echo "Building executable for ${{ matrix.os }}"
          pyinstaller --onefile src/main.py
          echo "Build complete. Checking dist directory..."
          ls dist  # List contents of the dist directory to confirm output

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-exe  # Consistent naming for artifacts
          path: dist/*                  # Upload all files in the dist directory

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-exe
          path: ./artifacts/windows

      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-exe
          path: ./artifacts/linux

      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-exe
          path: ./artifacts/macos

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            ## Release v${{ github.run_number }}
            This release includes the following executables:
            - Windows: `windows-exe`
            - Linux: `linux-exe`
            - macOS: `macos-exe`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows executable to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}  # Use the existing tag
          files: ./artifacts/windows/*  # Specify the files to upload
          token: ${{ secrets.GITHUB_TOKEN }}  # Required token for authorization

      - name: Upload Linux executable to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}  # Use the existing tag
          files: ./artifacts/linux/*  # Specify the files to upload
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS executable to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}  # Use the existing tag
          files: ./artifacts/macos/*  # Specify the files to upload
          token: ${{ secrets.GITHUB_TOKEN }}