name: Build Python Executables

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile your_script.py
      
      - name: Upload Windows executable
        uses: actions/upload-artifact@v2
        with:
          name: windows-exe
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile your_script.py
      
      - name: Upload Linux executable
        uses: actions/upload-artifact@v2
        with:
          name: linux-exe
          path: dist/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      
      - name: Build executable
        run: pyinstaller --onefile your_script.py
      
      - name: Upload macOS executable
        uses: actions/upload-artifact@v2
        with:
          name: macos-exe
          path: dist/

